# Generated by Django 5.0.4 on 2024-04-04 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('contraseña', models.CharField(max_length=100)),
                ('perfil', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('cantidad_mascotas', models.IntegerField(default=0)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('raza', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('descripcion_fisica', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion_personalidad', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas')),
                ('alimento', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ficha_mascotas.usuarios')),
            ],
        ),
    ]
